name: windows_store
description: A flutter plugin for retrieving license information from Microsoft Store apps.
version: 1.0.0
repository: https://github.com/SongbookPro/flutter_windows_store

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.28.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  pigeon: ^26.0.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: WindowsStorePluginCApi
