// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace windows_store {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class WindowsStoreApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


// Represents the kind of product available in the Microsoft Store.
// https://learn.microsoft.com/en-us/uwp/api/windows.services.store.storeproduct.productkind?view=winrt-26100#windows-services-store-storeproduct-productkind
enum class StoreProductKind {
  kApplication = 0,
  kGame = 1,
  kConsumable = 2,
  kUnmanagedConsumable = 3,
  // An add-on that persists for the lifetime that you specify in Partner Center. 
  // By default, durable add-ons never expire, in which case they can only be purchased once. 
  // If you specify a particular duration for the add-on, the user can repurchase the add-on after it expires.
  // Note: A StoreProduct that represents a subscription add-on has the type Durable.
  kDurable = 4
};


// Generated class from Pigeon that represents data sent in messages.
class StoreAppLicenseInner {
 public:
  // Constructs an object setting all fields.
  explicit StoreAppLicenseInner(
    bool is_active,
    bool is_trial,
    const std::string& sku_store_id,
    const std::string& trial_unique_id,
    int64_t trial_time_remaining);

  bool is_active() const;
  void set_is_active(bool value_arg);

  bool is_trial() const;
  void set_is_trial(bool value_arg);

  const std::string& sku_store_id() const;
  void set_sku_store_id(std::string_view value_arg);

  const std::string& trial_unique_id() const;
  void set_trial_unique_id(std::string_view value_arg);

  int64_t trial_time_remaining() const;
  void set_trial_time_remaining(int64_t value_arg);

 private:
  static StoreAppLicenseInner FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class WindowsStoreApi;
  friend class PigeonInternalCodecSerializer;
  bool is_active_;
  bool is_trial_;
  std::string sku_store_id_;
  std::string trial_unique_id_;
  int64_t trial_time_remaining_;
};


// Contains pricing info for a product listing in the Microsoft Store.
// https://learn.microsoft.com/en-us/uwp/api/windows.services.store.storeprice?view=winrt-26100
//
// Generated class from Pigeon that represents data sent in messages.
class StorePriceInner {
 public:
  // Constructs an object setting all fields.
  explicit StorePriceInner(
    const std::string& currency_code,
    bool is_on_sale,
    const std::string& sale_end_date,
    const std::string& formatted_base_price,
    const std::string& formatted_price,
    const std::string& formatted_recurrence_price);

  // Gets the ISO 4217 currency code for the market of the current user.
  const std::string& currency_code() const;
  void set_currency_code(std::string_view value_arg);

  // Gets a value that indicates whether the product is on sale.
  bool is_on_sale() const;
  void set_is_on_sale(bool value_arg);

  // Gets the end date for the sale period for the product, if the product is on sale. (ISO 8601) 
  const std::string& sale_end_date() const;
  void set_sale_end_date(std::string_view value_arg);

  // Gets the base price for the product with the appropriate formatting for the market of the current user.
  const std::string& formatted_base_price() const;
  void set_formatted_base_price(std::string_view value_arg);

  // Gets the purchase price for the product with the appropriate formatting for the market of the current user.
  const std::string& formatted_price() const;
  void set_formatted_price(std::string_view value_arg);

  // Gets the recurring price for the product with the appropriate formatting for the market of the current user, if recurring billing is enabled for this product.
  const std::string& formatted_recurrence_price() const;
  void set_formatted_recurrence_price(std::string_view value_arg);

 private:
  static StorePriceInner FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class StoreProductInner;
  friend class WindowsStoreApi;
  friend class PigeonInternalCodecSerializer;
  std::string currency_code_;
  bool is_on_sale_;
  std::string sale_end_date_;
  std::string formatted_base_price_;
  std::string formatted_price_;
  std::string formatted_recurrence_price_;
};


// Add-on associated to the application in the Microsoft Store
// https://learn.microsoft.com/en-us/uwp/api/windows.services.store.storeproduct?view=winrt-26100
//
// Generated class from Pigeon that represents data sent in messages.
class StoreProductInner {
 public:
  // Constructs an object setting all fields.
  explicit StoreProductInner(
    const std::string& store_id,
    const std::string& description,
    const std::string& title,
    const std::string& in_app_offer_token,
    const StoreProductKind& product_kind,
    const StorePriceInner& price);

  ~StoreProductInner() = default;
  StoreProductInner(const StoreProductInner& other);
  StoreProductInner& operator=(const StoreProductInner& other);
  StoreProductInner(StoreProductInner&& other) = default;
  StoreProductInner& operator=(StoreProductInner&& other) noexcept = default;
  // Gets the Store ID for this product. For an add-on, this property corresponds to the Store ID that is available on the overview page for the add-on.
  const std::string& store_id() const;
  void set_store_id(std::string_view value_arg);

  // Gets the product description from the Microsoft Store listing.
  const std::string& description() const;
  void set_description(std::string_view value_arg);

  // Gets the product title from the Microsoft Store listing.
  const std::string& title() const;
  void set_title(std::string_view value_arg);

  // Gets the product ID for this product, if the current StoreProduct represents an add-on.
  const std::string& in_app_offer_token() const;
  void set_in_app_offer_token(std::string_view value_arg);

  // Gets the type of the product.
  const StoreProductKind& product_kind() const;
  void set_product_kind(const StoreProductKind& value_arg);

  // Gets the price for the default SKU and availability for the product.
  const StorePriceInner& price() const;
  void set_price(const StorePriceInner& value_arg);

 private:
  static StoreProductInner FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class WindowsStoreApi;
  friend class PigeonInternalCodecSerializer;
  std::string store_id_;
  std::string description_;
  std::string title_;
  std::string in_app_offer_token_;
  StoreProductKind product_kind_;
  std::unique_ptr<StorePriceInner> price_;
};


// Generated class from Pigeon that represents data sent in messages.
class AssociatedStoreProductsInner {
 public:
  // Constructs an object setting all fields.
  explicit AssociatedStoreProductsInner(const flutter::EncodableList& products);

  const flutter::EncodableList& products() const;
  void set_products(const flutter::EncodableList& value_arg);

 private:
  static AssociatedStoreProductsInner FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class WindowsStoreApi;
  friend class PigeonInternalCodecSerializer;
  flutter::EncodableList products_;
};


class PigeonInternalCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;
 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;
};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class WindowsStoreApi {
 public:
  WindowsStoreApi(const WindowsStoreApi&) = delete;
  WindowsStoreApi& operator=(const WindowsStoreApi&) = delete;
  virtual ~WindowsStoreApi() {}
  virtual void GetAppLicenseAsync(std::function<void(ErrorOr<StoreAppLicenseInner> reply)> result) = 0;
  // Gets Microsoft Store listing info for the products that can be purchased from within the current app.
  // productKind: The kind of product to retrieve.
  virtual void GetAssociatedStoreProductsAsync(
    const StoreProductKind& product_kind,
    std::function<void(ErrorOr<AssociatedStoreProductsInner> reply)> result) = 0;

  // The codec used by WindowsStoreApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `WindowsStoreApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    WindowsStoreApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    WindowsStoreApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  WindowsStoreApi() = default;
};
}  // namespace windows_store
#endif  // PIGEON_MESSAGES_G_H_
